version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
