version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  nats:
    image: nats:latest
    container_name: brainrush-nats
    restart: always
    ports:
      - "4222:4222"  # Cliente para conexiones 
      - "8222:8222"  # Puerto HTTP para monitoreo
      - "6222:6222"  # Puerto de enrutamiento para clusters
    command: -js -m 8222

volumes:
  postgres_data:
    driver: local
