name: Deploy to Digital Ocean

on:
  push:
    branches: [main] # Cambia a 'master' si usas esa rama como principal
    paths-ignore:
      - '**.md' # Ignora cambios en archivos markdown

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build applications
        run: |
          npx nx build api-gateway --prod
          npx nx build auth-service --prod

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env.prod
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.prod
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env.prod
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.prod
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env.prod

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            # Crear directorio del proyecto si no existe
            mkdir -p /home/brainrush/brainrush-app

            # Ir al directorio del proyecto
            cd /home/brainrush/brainrush-app

            # Transferir archivos

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: 'dist/,docker-compose.prod.yml,.env.prod,apps/*/Dockerfile'
          target: '/home/brainrush/brainrush-app'
          strip_components: 0

      - name: Start Docker containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /home/brainrush/brainrush-app
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build

            # Ejecutar migraciones de Prisma (si aplica)
            docker compose -f docker-compose.prod.yml exec -T auth-service npx prisma migrate deploy

            # Eliminar imágenes antiguas (limpieza)
            docker image prune -af
